import Lexicon

import Lexicon.Documents: config, section, document, page, pages, preformat

import Lexicon.Utilities: packagemodules

import Lexicon.Extensions: title, header, subheader, text, textfile, objs

import Lexicon.Render: save, markdown

import Docile

import Docile: Cache, Collector

out = document("TestDocumentation",
    section("Introduction",
        page("index",
            textfile("index.md"),
            ),
        ),
    section("Manual",
        page("Overview",
            textfile("manual.md"),
            ),
        page("Syntax",
            textfile("syntax.md"),
            ),
        page("Metamacros",
            textfile("metamacros.md"),
            ),
        ),
    section("API", config(style_title="#", style_header="##", style_subheader="###"),
        page("Docile", config(style_subheader="*"),
            title("Docile"),
            header("Modules"),
            objs(Docile, :module),
            header("Methods & Macros"),
            subheader("Methods"),
            objs(Docile, :method),
            subheader("Macros"),
            text("Some intermediate text describing more about macros."),
            objs(Docile, :macro),
            ),
        page("Docile.Cache",
            title("Docile.Cache"),
            header("Modules"),
            objs(Docile.Cache, :module),
            header("Methods & Macros"; style_header="#"),
            subheader("Methods"),
            objs(Docile.Cache, :method),
            subheader("Macros"),
            text("Some intermediate text describing more about macros."),
            objs(Docile.Cache, :macro),
            ),
        page("Docile.Collector",
            title("Docile.Collector"),
            header("ALL documented objects"),
            objs(Cache.objects(Docile.Collector)),
            ),
        ),
    section("Docile",
        pages("Group of pages",
            page("Modules",
                header("Modules TEXT"),
                text("Some intermediate text."),
                ),
            page("Macros",
                header("Macros TEXT"),
                ),
            ),
        ),
    ## ***************** High level
    # Multi-modules (e.g. package) Section: each module within a separate page
    section("Multi-Module API", config(autogenerate_categories=[:method], autogenerate_internal=false),
        packagemodules(Docile),
        ),
    # Single module section: each category within a separate page
    section(Cache, config(autogenerate_categories=[:module, :method, :macro], autogenerate_internal=true)),
    section("API-Autogenerated",
        # Single module page: all categories within one page
        page(Cache, config(autogenerate_categories=[:module, :method, :macro], autogenerate_internal=false)),
         ),
    )


#println("\n\n out:typeof: ", typeof(out), " out: \n\n", out)

#rmd = markdown("outdir", out)
#println("\n\n rmd: ", typeof(rmd), " rmd: \n\n", rmd)


save(markdown("out", out); remove_destination=true)
