site_name:           Docile.jl
repo_url:            https://github.com/MichaelHatherly/Docile.jl
site_description:    Julia package documentation system.
site_author:         Michael Hatherly
theme:               readthedocs

pages:
- Introduction:     index.md
- Manual:
    - Overview:     manual.md
    - Syntax:       syntax.md
    - Metamacros:   metamacros.md
- API:
    - Docile:               api/Docile.md
    - Docile.Cache:         api/Docile.Cache.md
    - Docile.Collector:     api/Docile.Collector.md
    - Docile.Extensions:    api/Docile.Extensions.md
    - Docile.Formats:       api/Docile.Formats.md
    - Docile.Interface:     api/Docile.Interface.md
    - Docile.Legacy:        api/Docile.Legacy.md
    - Docile.Runner:        api/Docile.Runner.md
    - Docile.Utilities:     api/Docile.Utilities.md
    - Index:                api/index.md

markdown_extensions:
    - tables
    - fenced_code
