site_name:           Lexicon.jl
repo_url:            https://github.com/MichaelHatherly/Lexicon.jl
site_description:    Julia package documentation generator.
site_author:         Michael Hatherly
theme:               flatly
markdown_extensions: [tables, fenced_code]
pages:
    - ['index.md', 'Introduction']
    - ['manual.md', 'Manual', 'Overview']
    - ['api/Lexicon.md', 'API', 'Lexicon']
    - ['api/index.md', 'API', 'Index']
